// <auto-generated />
using System;
using CidatAPP.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CidatAPP.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260301180815_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CidatAPP.Domain.Entities.FailedLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FAILEDLOGINATTEMPTS", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Fotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FILEURL");

                    b.Property<string>("FotoNome")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FOTONOME");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IDUSUARIO] IS NOT NULL");

                    b.ToTable("FOTOS", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.GrupoNiveis", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.HasKey("IdUsuario", "Id");

                    b.HasIndex("Id");

                    b.ToTable("GRUPONIVEL", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.GrupoSetores", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("IdSetor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSETOR");

                    b.HasKey("IdUsuario", "Id");

                    b.HasIndex("IdSetor");

                    b.ToTable("GRUPOSETORES", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHoraAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORAACESSO");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("MENSAGEM");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit")
                        .HasColumnName("SUCESSO");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LOGINHISTORY", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Niveis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeNivel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMENIVEL");

                    b.HasKey("Id");

                    b.ToTable("NIVEL", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMESETOR");

                    b.HasKey("Id");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Login")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.FailedLoginAttempt", b =>
                {
                    b.HasOne("CidatAPP.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Fotos", b =>
                {
                    b.HasOne("CidatAPP.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Fotos")
                        .HasForeignKey("CidatAPP.Domain.Entities.Fotos", "IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.GrupoNiveis", b =>
                {
                    b.HasOne("CidatAPP.Domain.Entities.Niveis", "Niveis")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidatAPP.Domain.Entities.Usuario", "Usuario")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveis");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.GrupoSetores", b =>
                {
                    b.HasOne("CidatAPP.Domain.Entities.Setor", "Setor")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CidatAPP.Domain.Entities.Usuario", "Usuario")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("CidatAPP.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Niveis", b =>
                {
                    b.Navigation("GrupoNiveis");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Setor", b =>
                {
                    b.Navigation("GrupoSetores");
                });

            modelBuilder.Entity("CidatAPP.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("GrupoNiveis");

                    b.Navigation("GrupoSetores");
                });
#pragma warning restore 612, 618
        }
    }
}
